apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-todos
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-todos
  template:
    metadata:
      labels:
        app: backend-todos
    spec:
      containers:
        - name: backend-todos
          image: PROJECT/backend-todos
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: todo-backend-config
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: PGPASSWORD
