apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: project
data:
  PORT: "3001"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://frontend.project.svc.cluster.local"
  PGUSER: "todoappuser"
  PGDATABASE: "tododb"
  PGPORT: "80"
  PGHOST: "postgres-svc.project.svc.cluster.local"
