apiVersion: v1
kind: ConfigMap
metadata:
  name: pingpong-config
  namespace: exercises
data:
  PGHOST: "postgres-svc.exercises.svc.cluster.local"
  PGUSER: "pingponguser"
  PGDATABASE: "pingpongdb"
  PGPORT: "80"
  PORT: "3000"
