apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: exercises
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS counter (
      id SERIAL PRIMARY KEY,
      value INTEGER NOT NULL DEFAULT 0
    );
    INSERT INTO counter (value)
    VALUES (0);