name: Build and publish application

on:
  push:
    paths:
      - 1.2/jobs/**

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: pingpong

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug secrets presence
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "❌ DOCKERHUB_USERNAME is empty"
          else
            echo "✅ DOCKERHUB_USERNAME is set"
          fi

          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN is empty"
          else
            echo "✅ DOCKERHUB_TOKEN is set"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        working-directory: 1.2/jobs
        run: |-
          docker build --tag "shehzadkhuwaja/todo-cronjob:$GITHUB_SHA" .
          docker push "shehzadkhuwaja/todo-cronjob:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        working-directory: 1.2
        run: kustomize edit set image project/todo-cronjob=shehzadkhuwaja/todo-cronjob:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: '1.2/kustomization.yaml'
          message: New version released ${{ github.sha }}