name: Build and publish application

on:
  push:
    paths:
      - ping-pong-with-log-output/1.1/string-reader/**

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    environment: pingpong

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        working-directory: ping-pong-with-log-output/1.1/string-reader
        run: |-
          docker build --tag "shehzadkhuwaja/string-reader:$GITHUB_SHA" .
          docker push "shehzadkhuwaja/string-reader:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        working-directory: ping-pong-with-log-output
        run: kustomize edit set image exercises/string-reader=shehzadkhuwaja/string-reader:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'ping-pong-with-log-output/kustomization.yaml'
          message: New version released ${{ github.sha }}